
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author angga
 */
public class tarik extends javax.swing.JFrame {


    public tarik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTARIKUANG = new javax.swing.JTextField();
        buttonTARIK = new javax.swing.JButton();
        buttonBACK = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 19)); // NOI18N
        jLabel2.setText("ANJUNGAN TUNAI MANDIRI");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 10, 260, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel1.setText("Tarik Tunai ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 190, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Jumlah uang :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 240, 100, 30);

        txtTARIKUANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTARIKUANGActionPerformed(evt);
            }
        });
        jPanel1.add(txtTARIKUANG);
        txtTARIKUANG.setBounds(150, 240, 230, 30);

        buttonTARIK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonTARIK.setText("TARIK");
        buttonTARIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTARIKActionPerformed(evt);
            }
        });
        jPanel1.add(buttonTARIK);
        buttonTARIK.setBounds(60, 310, 120, 40);

        buttonBACK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonBACK.setText("KEMBALI");
        buttonBACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBACKActionPerformed(evt);
            }
        });
        jPanel1.add(buttonBACK);
        buttonBACK.setBounds(230, 310, 120, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon("F:\\11R4\\PBO\\modul10\\Yes_Bank_logo.png")); // NOI18N
        jLabel6.setText("jLabel1");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 50, 300, 120);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 420, 420);

        setBounds(0, 0, 435, 459);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBACKActionPerformed
        this.setVisible(false);
        new transaksi().setVisible(true);
    }//GEN-LAST:event_buttonBACKActionPerformed

    private void buttonTARIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTARIKActionPerformed
        String tarikan = txtTARIKUANG.getText();
            int saldo = 200000;
            int jmltarik = Integer.parseInt(tarikan);
            int saldoakhir = saldo-jmltarik;
            
            if(jmltarik%100!=0)
            JOptionPane.showMessageDialog(null, "Mesin ATM BRI tidak menerima uang koin \nSilahkan ulagi Lagi", "Transaksi Gagal",0);
        else{
            if(jmltarik>saldo)
            JOptionPane.showMessageDialog(null, "Saldo anda tidak mencukupi \nSilahkan melakukan penyetoran", "Transaksi Gagal",0); 
            else if(jmltarik<50000)
            JOptionPane.showMessageDialog(null, "Besaran minimal pengambilan tunai adalah Rp.50.000,00", "Transaksi Gagal",0);
            else{
                saldo = saldo-jmltarik;
                JOptionPane.showMessageDialog(null, "Saldo anda saat ini sebesar " + saldo);
                if (saldo<=50000)
                {
                    JOptionPane.showMessageDialog(null,"Saldo minimal harus RP 50000,00 , Segera melakukan penyetoran untuk menghindari penutupan akun", "CAUTION", 2);
                }
            }
        }
    }//GEN-LAST:event_buttonTARIKActionPerformed

    private void txtTARIKUANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTARIKUANGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTARIKUANGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tarik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBACK;
    private javax.swing.JButton buttonTARIK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtTARIKUANG;
    // End of variables declaration//GEN-END:variables
}
