
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author angga
 */
public class transaksi extends javax.swing.JFrame {

    
    public transaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buttonSALDO = new javax.swing.JButton();
        buttonSETOR = new javax.swing.JButton();
        buttonTARIK = new javax.swing.JButton();
        buttonKELUAR = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 19)); // NOI18N
        jLabel2.setText("ANJUNGAN TUNAI MANDIRI");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 20, 260, 30);

        buttonSALDO.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        buttonSALDO.setText("Informasi Saldo");
        buttonSALDO.setToolTipText("");
        buttonSALDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSALDOActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSALDO);
        buttonSALDO.setBounds(50, 200, 150, 40);

        buttonSETOR.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        buttonSETOR.setText("Setor Tunai");
        buttonSETOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSETORActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSETOR);
        buttonSETOR.setBounds(50, 270, 150, 40);

        buttonTARIK.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        buttonTARIK.setText("Tarik Tunai ");
        buttonTARIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTARIKActionPerformed(evt);
            }
        });
        jPanel1.add(buttonTARIK);
        buttonTARIK.setBounds(250, 200, 150, 40);

        buttonKELUAR.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        buttonKELUAR.setText("Keluar");
        buttonKELUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKELUARActionPerformed(evt);
            }
        });
        jPanel1.add(buttonKELUAR);
        buttonKELUAR.setBounds(250, 270, 150, 40);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 10, 200, 60);

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\11R4\\PBO\\modul10\\Yes_Bank_logo.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 60, 300, 120);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 450, 340);

        setBounds(0, 0, 464, 378);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSALDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSALDOActionPerformed
        int saldo = 200000;
        JOptionPane.showMessageDialog(null, "Saldo anda saat ini adalah Rp " + saldo);
    }//GEN-LAST:event_buttonSALDOActionPerformed

    private void buttonKELUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKELUARActionPerformed
        JOptionPane.showMessageDialog(null,"SILAHKAN AMBIL KARTU ATM ANDA !","TERIMAKASIH",JOptionPane.WARNING_MESSAGE);
            System.exit(0);
    }//GEN-LAST:event_buttonKELUARActionPerformed

    private void buttonTARIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTARIKActionPerformed
        this.setVisible(false);
        new tarik().setVisible(true);
    }//GEN-LAST:event_buttonTARIKActionPerformed

    private void buttonSETORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSETORActionPerformed
        this.setVisible(false);
        new setor().setVisible(true);
    }//GEN-LAST:event_buttonSETORActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKELUAR;
    private javax.swing.JButton buttonSALDO;
    private javax.swing.JButton buttonSETOR;
    private javax.swing.JButton buttonTARIK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
